// Auto-generated by preprocess.ts — DO NOT EDIT
// XOR key parts (obfuscated: reassembled at runtime)
export const KEY_PART_A: u8[] = [0x5a, 0x3c, 0x69, 0x12, 0x8f, 0xa4, 0x27, 0xde];
export const KEY_PART_B: u8[] = [0x71, 0x09, 0xb3, 0xe6, 0x2d, 0xc8, 0x54, 0x77];
export const KEY_LEN: u32 = 16;
export const ENTRY_SIZE: u32 = 19; // 1 type + 10 date + 8 time
